Add a global cache layer common for all the endpoints
krakendio/krakend-jose pull request #112
Opened 2023-03-15 15:39 UTC by taik0

to reduce pressure on the JWK backends.

2023-03-17 11:02 UTC, dhontecillas commented on key_cacher.go
> +	}
here is where I would check if we already have a reference:
```go
var gc GlobalCacher
if kc, ok := globalKeyCacher[keyIdentifyStrategy]; ok {
    gc := kc
} else {
    return nil, fmt.Errorf("invalid strategy %s", gkc.strategy)
}
```

2023-03-17 18:55 UTC, alombarte requested changes
The namespace `auth/jose` is needed to load this configuration at the service level

2023-03-17 18:55 UTC, alombarte commented on key_cacher.go
> +			l.Error("[SERVICE: JWTValidator]", err.Error())
`[SERVICE: JOSE]`

2023-03-17 18:55 UTC, alombarte commented on key_cacher.go
> +	duration, ok := e["cache_duration"].(string)
`shared_cache_duration`

2023-03-17 18:55 UTC, alombarte commented on key_cacher.go
> +	return time.ParseDuration(duration)
Duration should be an uint32 expressing seconds, as we have on the `cache_duration`

2023-03-22 15:44 UTC, kpacha approved these changes

2023-03-22 17:06 UTC, alombarte requested changes

2023-04-18 14:01 UTC, merged